chip_size: 224
number_of_folds: 5
search_dates: '2019-03-01T00:00:00.000Z/2019-10-01T00:00:00.000Z'
max_cloud_cover: 5
zueri_crop:
  bbox: [8.364, 47.240, 9.0405, 47.69894] # new bbox is 5120x5120 pixels to accomodate for a nicer chip size of 20x20 256x256-chips; Old Bounding Box was [8.364, 47.240, 9.000, 47.697]
paths:
  chips: data/chips
  chips_stats: data/chips_stats.yaml
  satellite: data/satellite
  models: prithvi/models
  labels: data/labels.tif
  labels_hierarchy: data/labels_hierarchy.tif
  field_ids: data/field_ids.tif
  stacked_features: data/stacked_features.tif
  tier_names: data/tier_names.json
timespans:
  number_of_timespans: 3
  start: '2019-03-01'
  end: '2019-10-01'
number_of_bands: 6